# Generated by Django 5.2.6 on 2025-10-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_emp', models.CharField(max_length=100)),
                ('ap_p_emp', models.CharField(max_length=100)),
                ('ap_m_emp', models.CharField(blank=True, max_length=100)),
                ('direccion_emp', models.CharField(blank=True, max_length=200)),
                ('correo_emp', models.EmailField(blank=True, max_length=100)),
                ('puesto_emp', models.CharField(blank=True, max_length=100)),
                ('proyectos_emp', models.IntegerField(default=0)),
                ('foto_empleado', models.ImageField(blank=True, null=True, upload_to='img_empleados/')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pr', models.CharField(max_length=100)),
                ('direccion_pr', models.CharField(blank=True, max_length=200)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_pr', models.CharField(blank=True, max_length=50)),
                ('presupuesto_pr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app_empleado.empleado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
